from enum import Enum


class ErrorCode(str, Enum):
    # auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    REFRESH_REUSE_DETECTED = "REFRESH_REUSE_DETECTED"

    # member
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"

    # request
    VALIDATION_ERROR = "VALIDATION_ERROR"
    BAD_REQUEST = "BAD_REQUEST"

    # server
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
